import type { PresetConfig } from "./preset"

/** Design systems shown in `farsiui init` / `add` — Finglish titles only. */
export const DESIGN_SYSTEM_INSTALL_PRESETS = [
  {
    id: "default",
    title: "Default",
    description: "Standard and clear",
    style: "nova",
  },
  {
    id: "comfort",
    title: "Aram",
    description: "Soft and open",
    style: "vega",
  },
  {
    id: "glass",
    title: "Firoozeh",
    description: "Glass turquoise",
    style: "glass",
  },
  {
    id: "rose",
    title: "Rose",
    description: "Warm and soft",
    style: "rose",
  },
  {
    id: "nili",
    title: "Nili",
    description: "Cool and dark",
    style: "nili",
  },
  {
    id: "khesht",
    title: "Khesht",
    description: "Earthy and bold",
    style: "khesht",
  },
] as const

export type DesignSystemInstallId =
  (typeof DESIGN_SYSTEM_INSTALL_PRESETS)[number]["id"]

export const DEFAULT_PRESETS = {
  nova: {
    title: "Default",
    description: "Standard and clear",
    style: "nova",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  vega: {
    title: "Aram",
    description: "Soft and open",
    style: "vega",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  maia: {
    title: "Maia",
    description: "Hugeicons / Figtree",
    style: "maia",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "figtree",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  lyra: {
    title: "Lyra",
    description: "Phosphor / JetBrains Mono",
    style: "lyra",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "phosphor",
    font: "jetbrains-mono",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  mira: {
    title: "Mira",
    description: "Hugeicons / Inter",
    style: "mira",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  luma: {
    title: "Luma",
    description: "Lucide / Inter",
    style: "luma",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  sera: {
    title: "Sera",
    description: "Lucide / Noto Sans + Playfair Display",
    style: "sera",
    baseColor: "taupe",
    theme: "taupe",
    chartColor: "taupe",
    iconLibrary: "lucide",
    font: "noto-sans",
    fontHeading: "playfair-display",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  rhea: {
    title: "Rhea",
    description: "Lucide / Inter",
    style: "rhea",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  aether: {
    title: "Aether",
    description: "Lucide / Geist",
    style: "aether",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  glass: {
    title: "Firoozeh",
    description: "Glass turquoise",
    style: "glass",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  rose: {
    title: "Rose",
    description: "Warm and soft",
    style: "rose",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  nili: {
    title: "Nili",
    description: "Cool and dark",
    style: "nili",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  khesht: {
    title: "Khesht",
    description: "Earthy and bold",
    style: "khesht",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
} satisfies Record<
  PresetConfig["style"],
  PresetConfig & {
    description: string
    rtl: boolean
    title: string
  }
>
